"""
fraud_eda_agent.py  —  Vertex AI edition
=========================================
Agentic Fraud EDA using Gemini 2.0 Flash on Vertex AI.
Generates a fully populated Jupyter notebook from any transaction DataFrame.

Usage:
    import pandas as pd
    from fraud_eda_agent import FraudEDAAgent

    df = pd.read_csv("transactions.csv")
    agent = FraudEDAAgent(project="my-gcp-project", location="us-central1")
    agent.run(df, target_col="is_fraud", output="fraud_eda_report.ipynb")

Authentication (pick one):
    1. Local dev :  gcloud auth application-default login
    2. Workbench :  automatic via attached service account
    3. Cloud Run :  automatic via attached service account

Requirements:
    pip install -r requirements.txt
"""

from __future__ import annotations

import json
import os
import textwrap
from pathlib import Path
from typing import Optional

import nbformat
import nbformat.v4 as nbf
import pandas as pd
import numpy as np
from scipy import stats as scipy_stats

import vertexai
from vertexai.generative_models import (
    FunctionDeclaration,
    GenerativeModel,
    Tool,
    GenerationConfig,
)


# ─────────────────────────────────────────────────────────────────────────────
# Notebook builder
# ─────────────────────────────────────────────────────────────────────────────

class NotebookBuilder:
    """Wraps nbformat to make programmatic cell injection simple."""

    def __init__(self, title: str = "Fraud EDA Report"):
        self.nb = nbf.new_notebook()
        self.nb.metadata["kernelspec"] = {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3",
        }
        self._add_setup_cell()
        self.add_markdown(
            f"# {title}\n"
            "*Auto-generated by FraudEDAAgent — Vertex AI / Gemini 2.0 Flash*"
        )

    def _add_setup_cell(self):
        code = textwrap.dedent("""\
            import pandas as pd
            import numpy as np
            import matplotlib.pyplot as plt
            import seaborn as sns
            from scipy import stats
            import warnings
            warnings.filterwarnings('ignore')

            # ── Dark theme ───────────────────────────────────────────────────
            plt.rcParams.update({
                'figure.facecolor': '#0f1923',
                'axes.facecolor':   '#0f1923',
                'axes.edgecolor':   '#2a3f55',
                'axes.labelcolor':  '#8ab4cc',
                'axes.titlecolor':  '#c8dce8',
                'axes.titlesize':   13,
                'axes.labelsize':   11,
                'xtick.color':      '#5a7a8a',
                'ytick.color':      '#5a7a8a',
                'text.color':       '#c8dce8',
                'grid.color':       '#1e2d3a',
                'grid.linewidth':   0.5,
                'legend.facecolor': '#0f1923',
                'legend.edgecolor': '#2a3f55',
                'figure.dpi':       110,
            })
            FRAUD_COLOR  = '#ff4d6d'
            LEGIT_COLOR  = '#00c4b4'
            ACCENT_COLOR = '#00aaff'
            print("✓ Setup complete")
        """)
        self.nb.cells.append(nbf.new_code_cell(code))

    def add_markdown(self, text: str):
        self.nb.cells.append(nbf.new_markdown_cell(text))

    def add_code(self, code: str):
        self.nb.cells.append(nbf.new_code_cell(textwrap.dedent(code)))

    def save(self, path: str):
        Path(path).write_text(nbformat.writes(self.nb), encoding="utf-8")
        print(f"✓ Notebook saved → {path}")


# ─────────────────────────────────────────────────────────────────────────────
# Statistics helpers  (run locally, results fed to Gemini)
# ─────────────────────────────────────────────────────────────────────────────

def _compute_summary(df: pd.DataFrame, target: str) -> dict:
    fraud_mask = df[target].astype(int) == 1
    fraud_df   = df[fraud_mask]
    legit_df   = df[~fraud_mask]

    num_cols = [c for c in df.select_dtypes(include="number").columns if c != target]
    cat_cols = list(df.select_dtypes(include=["object", "category"]).columns)

    num_stats = []
    for col in num_cols:
        all_v = df[col].dropna()
        fr_v  = fraud_df[col].dropna()
        le_v  = legit_df[col].dropna()
        if len(all_v) == 0:
            continue
        entry = {
            "col":         col,
            "mean":        round(float(all_v.mean()), 4),
            "median":      round(float(all_v.median()), 4),
            "std":         round(float(all_v.std()), 4),
            "min":         round(float(all_v.min()), 4),
            "max":         round(float(all_v.max()), 4),
            "missing_pct": round(df[col].isna().mean() * 100, 2),
            "skew":        round(float(all_v.skew()), 3),
        }
        if len(fr_v) and len(le_v):
            entry["fraud_mean"] = round(float(fr_v.mean()), 4)
            entry["legit_mean"] = round(float(le_v.mean()), 4)
            entry["lift"] = (
                round(float(fr_v.mean() / le_v.mean()), 3)
                if le_v.mean() != 0 else None
            )
            try:
                _, pval = scipy_stats.mannwhitneyu(fr_v, le_v, alternative="two-sided")
                entry["mw_pval"] = round(float(pval), 6)
            except Exception:
                entry["mw_pval"] = None
        num_stats.append(entry)

    cat_stats = []
    for col in cat_cols[:8]:
        freq       = df[col].value_counts().head(8).to_dict()
        fraud_freq = fraud_df[col].value_counts().head(8).to_dict()
        cat_stats.append({"col": col, "top_values": freq, "fraud_top": fraud_freq})

    missing = {
        c: round(df[c].isna().mean() * 100, 2)
        for c in df.columns if df[c].isna().any()
    }

    return {
        "total_rows":   len(df),
        "fraud_count":  int(fraud_mask.sum()),
        "fraud_rate":   round(float(fraud_mask.mean() * 100), 3),
        "num_features": len(num_cols),
        "cat_features": len(cat_cols),
        "num_stats":    num_stats,
        "cat_stats":    cat_stats,
        "missing":      missing,
        "columns":      list(df.columns),
        "target":       target,
    }


# ─────────────────────────────────────────────────────────────────────────────
# Vertex AI Function Declarations  (equivalent to Anthropic tools)
# ─────────────────────────────────────────────────────────────────────────────

ADD_MARKDOWN = FunctionDeclaration(
    name="add_markdown_section",
    description="Add a markdown cell — section heading, narrative, or insight bullets.",
    parameters={
        "type": "object",
        "properties": {
            "content": {
                "type": "string",
                "description": "Markdown text to insert into the notebook.",
            }
        },
        "required": ["content"],
    },
)

ADD_CODE = FunctionDeclaration(
    name="add_code_cell",
    description=(
        "Add a Python code cell to the notebook. "
        "Pre-available variables: df, target_col, fraud_df, legit_df, "
        "FRAUD_COLOR, LEGIT_COLOR, ACCENT_COLOR, pd, np, plt, sns, stats. "
        "End every chart cell with plt.tight_layout() and plt.show()."
    ),
    parameters={
        "type": "object",
        "properties": {
            "code": {
                "type": "string",
                "description": "Runnable Python code to add.",
            },
            "purpose": {
                "type": "string",
                "description": "One-line description of what this cell does.",
            },
        },
        "required": ["code", "purpose"],
    },
)

FINISH = FunctionDeclaration(
    name="finish_notebook",
    description=(
        "Call this once all sections are written to signal the notebook is complete."
    ),
    parameters={
        "type": "object",
        "properties": {
            "summary": {
                "type": "string",
                "description": "2-3 sentence executive summary citing specific numbers.",
            }
        },
        "required": ["summary"],
    },
)

EDA_TOOLS = Tool(function_declarations=[ADD_MARKDOWN, ADD_CODE, FINISH])

# ─────────────────────────────────────────────────────────────────────────────
# System prompt
# ─────────────────────────────────────────────────────────────────────────────

SYSTEM_PROMPT = """You are a senior fraud data scientist generating an automated EDA notebook.
You receive dataset statistics and must produce a complete, professional Jupyter notebook
by calling tools in this exact order:

1.  add_markdown_section  — Executive summary: fraud rate, top risk signals, data quality
2.  add_code_cell         — Dataset overview: df.info(), shape, dtypes
3.  add_code_cell         — Missing value heatmap (seaborn)
4.  add_code_cell         — Class imbalance bar chart with percentage annotations
5.  add_code_cell         — KDE overlays for top 4 numeric features (fraud vs legit)
6.  add_code_cell         — Feature lift table: sorted DataFrame of fraud_mean/legit_mean
7.  add_code_cell         — Categorical breakdown: grouped bar chart for top cat features
8.  add_code_cell         — Correlation heatmap of numeric features
9.  add_code_cell         — Mann-Whitney U p-values table, highlight p < 0.05
10. add_markdown_section  — Key findings & recommendations with specific numbers
11. finish_notebook       — Executive summary citing exact fraud rate and top signals

Rules:
- Every code cell must be self-contained and runnable without imports (already done in setup).
- Reference specific numbers from the stats JSON in every markdown cell.
- Use FRAUD_COLOR / LEGIT_COLOR / ACCENT_COLOR for all charts — never default matplotlib colors.
- Keep code clean with inline comments. No print statements except progress indicators.
- Call finish_notebook as the very last tool call.
"""


# ─────────────────────────────────────────────────────────────────────────────
# Agent
# ─────────────────────────────────────────────────────────────────────────────

class FraudEDAAgent:
    def __init__(
        self,
        project:  Optional[str] = None,
        location: str = "us-central1",
    ):
        """
        Parameters
        ----------
        project  : GCP project ID.  Falls back to GOOGLE_CLOUD_PROJECT env var
                   or the project inferred from Application Default Credentials.
        location : Vertex AI region.  us-central1 has the widest model availability.
        """
        self.project  = project or os.environ.get("GOOGLE_CLOUD_PROJECT")
        self.location = location

        vertexai.init(project=self.project, location=self.location)

        self.model = GenerativeModel(
            model_name="gemini-2.0-flash-001",
            system_instruction=SYSTEM_PROMPT,
            tools=[EDA_TOOLS],
            generation_config=GenerationConfig(
                temperature=0.2,   # low temp = consistent, structured output
                max_output_tokens=4096,
            ),
        )

    # ── public API ────────────────────────────────────────────────────────────

    def run(
        self,
        df:         pd.DataFrame,
        target_col: str = "is_fraud",
        output:     str = "fraud_eda_report.ipynb",
        focus:      Optional[str] = None,
        verbose:    bool = True,
    ) -> str:
        """
        Run the agentic EDA and write a .ipynb notebook.

        Parameters
        ----------
        df         : Transaction DataFrame
        target_col : Binary fraud label column (0/1 or False/True)
        output     : Output path for the .ipynb file
        focus      : Optional analyst hint, e.g. 'focus on velocity features'
        verbose    : Print progress to stdout

        Returns
        -------
        Absolute path to the saved notebook.
        """
        if target_col not in df.columns:
            raise ValueError(
                f"target_col '{target_col}' not in DataFrame. "
                f"Available columns: {list(df.columns)}"
            )

        if verbose:
            fraud_rate = df[target_col].astype(int).mean() * 100
            print(f"▶ Dataset: {len(df):,} rows | fraud rate: {fraud_rate:.2f}%")
            print("▶ Computing statistics...")

        summary = _compute_summary(df, target_col)
        nb      = NotebookBuilder(title="Fraud EDA Report")

        # Embed CSV so the notebook is fully self-contained
        # (first 200 k chars keeps it portable; trim for very large datasets)
        nb.add_code(f"""\
            import io
            _csv = {repr(df.to_csv(index=False)[:200_000])}
            df = pd.read_csv(io.StringIO(_csv))
            target_col = {repr(target_col)}
            fraud_df = df[df[target_col].astype(int) == 1].copy()
            legit_df = df[df[target_col].astype(int) == 0].copy()
            print(f"Loaded {{len(df):,}} rows  |  "
                  f"fraud: {{len(fraud_df):,}} ({{len(fraud_df)/len(df)*100:.2f}}%)")
        """)

        focus_clause = f"\n\nAnalyst focus: {focus}" if focus else ""
        opening_msg  = (
            f"Here are the dataset statistics:\n\n"
            f"```json\n{json.dumps(summary, indent=2)}\n```"
            f"{focus_clause}\n\n"
            "Build the complete EDA notebook now by calling the tools in sequence."
        )

        # ── Gemini multi-turn function-calling loop ───────────────────────────
        chat        = self.model.start_chat()
        pending_msg = opening_msg   # first user message
        done        = False
        cell_count  = 0

        while not done:
            if verbose:
                print(f"  → Gemini reasoning (cells written: {cell_count})...")

            response = chat.send_message(pending_msg)
            pending_msg = []   # subsequent turns carry only function responses

            candidate = response.candidates[0]

            for part in candidate.content.parts:
                if not hasattr(part, "function_call") or not part.function_call:
                    continue

                fn   = part.function_call.name
                args = dict(part.function_call.args)

                # ── route to notebook builder ─────────────────────────────
                if fn == "add_markdown_section":
                    nb.add_markdown(args["content"])
                    cell_count += 1
                    if verbose:
                        preview = args["content"][:70].replace("\n", " ")
                        print(f"    + markdown : {preview}…")
                    pending_msg.append(self._fn_response(fn, "added"))

                elif fn == "add_code_cell":
                    nb.add_code(args["code"])
                    cell_count += 1
                    if verbose:
                        print(f"    + code     : {args.get('purpose', '')}")
                    pending_msg.append(self._fn_response(fn, "added"))

                elif fn == "finish_notebook":
                    nb.add_markdown(
                        f"---\n## Executive summary\n\n{args['summary']}\n\n"
                        "*Generated by FraudEDAAgent · Vertex AI / Gemini 2.0 Flash*"
                    )
                    done = True
                    if verbose:
                        print("  → finish_notebook called — wrapping up.")
                    pending_msg.append(self._fn_response(fn, "notebook complete"))

            # Guard: if Gemini stops calling functions without finish_notebook
            if not pending_msg:
                if verbose:
                    print("  → No more function calls — saving notebook.")
                done = True

        nb.save(output)
        abs_path = str(Path(output).resolve())

        if verbose:
            print(f"\n✓ {cell_count} cells written.")
            print(f"\nOpen locally  :  jupyter notebook {output}")
            print(f"Upload to GCS :  gsutil cp {output} gs://YOUR_BUCKET/notebooks/")
            print(f"Vertex WB     :  open from GCS in JupyterLab")

        return abs_path

    # ── helpers ───────────────────────────────────────────────────────────────

    @staticmethod
    def _fn_response(name: str, result: str) -> dict:
        """Build a Vertex AI function-response part."""
        return {
            "role": "user",
            "parts": [{
                "function_response": {
                    "name": name,
                    "response": {"result": result},
                }
            }],
        }
