"""
eda_agent.py  —  Vertex AI edition  (domain-agnostic)
======================================================
Agentic EDA using Gemini 2.0 Flash on Vertex AI.
Works with ANY tabular dataset: fraud, tennis, sales, medical, etc.

Two-phase design
----------------
Phase 1 — Planning:
    Gemini inspects a sample of the data and returns a structured JSON plan:
    domain, target column, task type (classification / regression / unsupervised),
    analysis goals, and the ordered list of notebook sections to generate.

Phase 2 — Generation:
    Gemini uses that plan as context to write every notebook cell —
    charts, statistics, and narrative are all tailored to the detected domain.

Usage:
    from eda_agent import EDAAgent
    import pandas as pd

    df = pd.read_csv("atp_matches.csv")
    agent = EDAAgent(project="my-gcp-project")
    agent.run(df, goal="analyse serve and win-rate patterns by surface")

    df2 = pd.read_csv("transactions.csv")
    agent.run(df2, target_col="is_fraud")   # explicit target still works

Authentication:
    Local  : gcloud auth application-default login
    GCP    : automatic via attached service account

Requirements:
    pip install -r requirements.txt
"""

from __future__ import annotations

import json
import os
import textwrap
from pathlib import Path
from typing import Optional

import nbformat
import nbformat.v4 as nbf
import pandas as pd
import numpy as np
from scipy import stats as scipy_stats

import vertexai
from vertexai.generative_models import (
    FunctionDeclaration,
    GenerativeModel,
    Tool,
    GenerationConfig,
    Part,
    Content,
)


# ─────────────────────────────────────────────────────────────────────────────
# Notebook builder
# ─────────────────────────────────────────────────────────────────────────────

class NotebookBuilder:
    def __init__(self, title: str = "EDA Report"):
        self.nb = nbf.new_notebook()
        self.nb.metadata["kernelspec"] = {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3",
        }
        self._add_setup_cell()
        self.add_markdown(
            f"# {title}\n"
            "*Auto-generated by EDAAgent — Vertex AI / Gemini 2.0 Flash*"
        )

    def _add_setup_cell(self):
        self.nb.cells.append(nbf.new_code_cell(textwrap.dedent("""\
            import pandas as pd
            import numpy as np
            import matplotlib.pyplot as plt
            import seaborn as sns
            from scipy import stats
            import warnings
            warnings.filterwarnings('ignore')

            plt.rcParams.update({
                'figure.facecolor': '#0f1923',
                'axes.facecolor':   '#0f1923',
                'axes.edgecolor':   '#2a3f55',
                'axes.labelcolor':  '#8ab4cc',
                'axes.titlecolor':  '#c8dce8',
                'axes.titlesize':   13,
                'axes.labelsize':   11,
                'xtick.color':      '#5a7a8a',
                'ytick.color':      '#5a7a8a',
                'text.color':       '#c8dce8',
                'grid.color':       '#1e2d3a',
                'grid.linewidth':   0.5,
                'legend.facecolor': '#0f1923',
                'legend.edgecolor': '#2a3f55',
                'figure.dpi':       110,
            })
            PRIMARY_COLOR   = '#00aaff'
            SECONDARY_COLOR = '#ff4d6d'
            ACCENT_COLOR    = '#00e5a0'
            print("✓ Setup complete")
        """)))

    def add_markdown(self, text: str):
        self.nb.cells.append(nbf.new_markdown_cell(text))

    def add_code(self, code: str):
        self.nb.cells.append(nbf.new_code_cell(textwrap.dedent(code)))

    def save(self, path: str):
        Path(path).write_text(nbformat.writes(self.nb), encoding="utf-8")
        print(f"✓ Notebook saved → {path}")


# ─────────────────────────────────────────────────────────────────────────────
# Statistics helpers
# ─────────────────────────────────────────────────────────────────────────────

def _compute_summary(df: pd.DataFrame, target: Optional[str]) -> dict:
    """
    Compute dataset statistics independently of domain.
    If target is provided, include per-class breakdowns.
    """
    num_cols = [
        c for c in df.select_dtypes(include="number").columns
        if c != target
    ]
    cat_cols = list(df.select_dtypes(include=["object", "category"]).columns)

    # ── numeric stats ────────────────────────────────────────────────────────
    num_stats = []
    for col in num_cols:
        vals = df[col].dropna()
        if len(vals) == 0:
            continue
        entry = {
            "col":         col,
            "mean":        round(float(vals.mean()), 4),
            "median":      round(float(vals.median()), 4),
            "std":         round(float(vals.std()), 4),
            "min":         round(float(vals.min()), 4),
            "max":         round(float(vals.max()), 4),
            "p25":         round(float(vals.quantile(0.25)), 4),
            "p75":         round(float(vals.quantile(0.75)), 4),
            "skew":        round(float(vals.skew()), 3),
            "missing_pct": round(df[col].isna().mean() * 100, 2),
        }

        # per-class breakdown if target is known and binary/categorical
        if target and target in df.columns:
            for cls_val in df[target].dropna().unique()[:5]:  # cap at 5 classes
                g = df[df[target] == cls_val][col].dropna()
                if len(g):
                    entry[f"mean__{cls_val}"] = round(float(g.mean()), 4)

            # Mann-Whitney for binary targets
            classes = df[target].dropna().unique()
            if len(classes) == 2:
                g1 = df[df[target] == classes[0]][col].dropna()
                g2 = df[df[target] == classes[1]][col].dropna()
                if len(g1) and len(g2):
                    try:
                        _, pval = scipy_stats.mannwhitneyu(
                            g1, g2, alternative="two-sided"
                        )
                        entry["mw_pval"] = round(float(pval), 6)
                        entry["lift"] = (
                            round(float(g1.mean() / g2.mean()), 3)
                            if g2.mean() != 0 else None
                        )
                    except Exception:
                        pass

        num_stats.append(entry)

    # ── categorical stats ────────────────────────────────────────────────────
    cat_stats = []
    for col in cat_cols[:10]:
        freq = df[col].value_counts().head(10).to_dict()
        entry = {"col": col, "n_unique": int(df[col].nunique()), "top_values": freq}
        if target and target in df.columns:
            # value counts per target class for top categories
            top_cats = list(freq.keys())[:6]
            per_class = {}
            for cls_val in df[target].dropna().unique()[:5]:
                sub = df[df[target] == cls_val][col]
                per_class[str(cls_val)] = sub.value_counts().reindex(
                    top_cats, fill_value=0
                ).to_dict()
            entry["per_class"] = per_class
        cat_stats.append(entry)

    # ── target stats (if available) ──────────────────────────────────────────
    target_stats = None
    if target and target in df.columns:
        t = df[target].dropna()
        is_numeric_target = pd.api.types.is_numeric_dtype(t)
        if is_numeric_target and t.nunique() > 10:
            target_stats = {
                "type": "continuous",
                "mean": round(float(t.mean()), 4),
                "std":  round(float(t.std()), 4),
                "min":  round(float(t.min()), 4),
                "max":  round(float(t.max()), 4),
            }
        else:
            vc = t.value_counts()
            target_stats = {
                "type":        "categorical",
                "n_classes":   int(t.nunique()),
                "class_counts": vc.to_dict(),
                "class_pcts":   (vc / len(t) * 100).round(2).to_dict(),
            }

    # ── sample rows (helps Gemini understand the data) ───────────────────────
    sample = df.head(5).to_dict(orient="records")
    # sanitize for JSON
    for row in sample:
        for k, v in row.items():
            if isinstance(v, float) and (np.isnan(v) or np.isinf(v)):
                row[k] = None

    missing = {
        c: round(df[c].isna().mean() * 100, 2)
        for c in df.columns if df[c].isna().any()
    }

    return {
        "shape":        {"rows": len(df), "cols": len(df.columns)},
        "columns":      list(df.columns),
        "dtypes":       {c: str(df[c].dtype) for c in df.columns},
        "target":       target,
        "num_stats":    num_stats,
        "cat_stats":    cat_stats,
        "target_stats": target_stats,
        "missing":      missing,
        "sample_rows":  sample,
    }


# ─────────────────────────────────────────────────────────────────────────────
# Phase 1 — Planning prompt & parser
# ─────────────────────────────────────────────────────────────────────────────

PLANNING_PROMPT = """You are a senior data scientist. You will receive a JSON summary of a dataset
and must return a structured analysis plan so a second AI pass can generate
the right notebook for this specific dataset.

Return ONLY valid JSON — no markdown, no prose, no code fences. Schema:

{{
  "title":        "Short descriptive report title",
  "domain":       "One of: fraud, sports, sales, medical, finance, marketing, hr, logistics, generic",
  "domain_label": "Human-friendly domain name, e.g. Tennis Match Statistics",
  "task_type":    "One of: binary_classification, multiclass_classification, regression, unsupervised",
  "target_col":   "The most meaningful target column name, or null if none",
  "target_label": "Human-friendly name for the target, e.g. Match Winner or null",
  "analysis_goals": ["3-5 specific goals for this dataset and domain"],
  "key_features": ["4-6 column names most likely to be predictive or interesting"],
  "sections": [
    {{
      "id":    "unique_snake_case_id",
      "title": "Section title",
      "type":  "one of: overview, target_distribution, numeric_distributions, categorical_breakdown, correlation, feature_importance, time_series, geographic, domain_specific, insights",
      "description": "What this section should show and why it matters for this domain"
    }}
  ],
  "domain_insights_prompt": "A domain-specific instruction for the AI writing the insights section, e.g. 'Focus on serve efficiency, break-point conversion, and surface differences'"
}}

Rules:
- sections must include at minimum: overview, target_distribution (if target exists),
  numeric_distributions, categorical_breakdown, correlation, and insights.
- Add domain_specific sections when the data warrants it (e.g. win/loss streaks for sports,
  cohort analysis for sales, survival curves for medical).
- key_features should be column names that actually exist in the dataset.
- If no obvious target column exists, set task_type to unsupervised and target_col to null.
- For the target_col: if the user provided one, use it. Otherwise infer the most meaningful one
  from column names and value distributions in the stats.
"""


def _run_planning(
    model: GenerativeModel,
    model_name: str,
    summary: dict,
    user_goal: Optional[str],
    user_target: Optional[str],
    user_context: Optional[str],
    verbose: bool,
) -> dict:
    """Phase 1: ask Gemini to produce a structured analysis plan."""
    context_block = ""
    if user_context:
        context_block = (
            "\n\n## Dataset description (provided by the user)\n"
            + user_context
            + "\nUse this to resolve column name ambiguity, understand what values "
            "represent, and tailor the analysis sections to this specific dataset."
        )
    target_hint = (
        f"\nTarget column (explicitly set by user): '{user_target}'"
        if user_target else ""
    )
    goal_hint = (
        f"\nAnalysis goal (set by user): \"{user_goal}\""
        if user_goal else ""
    )
    # Trim summary for planning — only needs structure, not full per-class stats
    # This prevents truncation on wide datasets with many numeric columns
    planning_summary = {
        "shape":        summary["shape"],
        "columns":      summary["columns"],
        "dtypes":       summary["dtypes"],
        "target":       summary["target"],
        "target_stats": summary["target_stats"],
        "missing":      summary["missing"],
        "sample_rows":  summary["sample_rows"][:3],
        # Slim numeric stats — just col name, mean, std, missing for planning
        "num_stats": [
            {k: v for k, v in s.items()
             if k in ("col", "mean", "std", "min", "max", "missing_pct", "skew", "lift", "mw_pval")}
            for s in summary["num_stats"]
        ],
        # Slim cat stats — just col name and top 5 values
        "cat_stats": [
            {"col": s["col"], "n_unique": s["n_unique"],
             "top_values": dict(list(s["top_values"].items())[:5])}
            for s in summary["cat_stats"]
        ],
    }

    prompt = (
        f"{PLANNING_PROMPT}"
        f"{context_block}\n\n"
        "Dataset statistics:\n"
        f"```json\n{json.dumps(planning_summary, indent=2)}\n```"
        f"{target_hint}{goal_hint}\n\n"
        "Return the analysis plan JSON now."
    )

    if verbose:
        print("  → Phase 1: planning...")

    planning_model = GenerativeModel(
        model_name=model_name,  # same model as generation
        generation_config=GenerationConfig(temperature=0.1, max_output_tokens=4096),
    )
    resp = planning_model.generate_content(prompt)
    raw  = resp.text.strip()

    # Strip markdown code fences if present
    if "```" in raw:
        raw = "\n".join(
            line for line in raw.splitlines()
            if not line.strip().startswith("```")
        ).strip()

    # Robust parse — handle truncated responses gracefully
    try:
        plan = json.loads(raw)
    except json.JSONDecodeError:
        if verbose:
            print("  → Planning response truncated, retrying with slim summary...")
        slim_summary = {
            "shape":       summary["shape"],
            "columns":     summary["columns"],
            "dtypes":      summary["dtypes"],
            "target":      summary["target"],
            "sample_rows": summary["sample_rows"][:3],
            "missing":     summary["missing"],
        }
        retry_prompt = (
            f"{PLANNING_PROMPT}"
            f"{context_block}\n\n"
            "Dataset statistics (condensed):\n"
            f"```json\n{json.dumps(slim_summary, indent=2)}\n```"
            f"{target_hint}{goal_hint}\n\n"
            "Return the analysis plan JSON now. Keep section descriptions brief."
        )
        resp2 = planning_model.generate_content(retry_prompt)
        raw2  = resp2.text.strip()
        if "```" in raw2:
            raw2 = "\n".join(
                line for line in raw2.splitlines()
                if not line.strip().startswith("```")
            ).strip()
        plan = json.loads(raw2)


    if verbose:
        print(f"  → Domain detected: {plan.get('domain_label', plan.get('domain'))}")
        print(f"  → Task type: {plan.get('task_type')}")
        print(f"  → Target: {plan.get('target_col')}")
        print(f"  → Sections planned: {len(plan.get('sections', []))}")

    return plan


def _build_generation_prompt(plan: dict, summary: dict) -> str:
    sections_text = "\n".join(
        f"  {i+1}. [{s['type']}] {s['title']} — {s['description']}"
        for i, s in enumerate(plan.get("sections", []))
    )
    return f"""You are a senior data scientist generating a Jupyter notebook EDA report.

Domain: {plan.get('domain_label', plan.get('domain'))}
Task type: {plan.get('task_type')}
Target column: {plan.get('target_col') or 'None (unsupervised)'}
Target label: {plan.get('target_label') or 'N/A'}

Analysis goals:
{chr(10).join(f'  - {g}' for g in plan.get('analysis_goals', []))}

Key features to focus on: {', '.join(plan.get('key_features', []))}

Sections to generate (in order):
{sections_text}

Domain-specific insight guidance:
{plan.get('domain_insights_prompt', 'Provide relevant statistical insights for this domain.')}

Dataset statistics for reference:
```json
{json.dumps(summary, indent=2)}
```

Rules:
- Generate cells in the exact section order above.
- Every code cell must be self-contained and runnable.
- Use PRIMARY_COLOR / SECONDARY_COLOR / ACCENT_COLOR for all charts.
- Reference specific numbers from the stats in every markdown narrative cell.
- For the target column use: target_col variable (already defined, may be None — check before use).
- For domain_specific sections, write creative, domain-appropriate analysis
  (e.g. for tennis: serve % by surface; for fraud: velocity patterns; for sales: cohort curves).
- Call finish_notebook last with a sharp, specific executive summary.
"""


# ─────────────────────────────────────────────────────────────────────────────
# Phase 2 — Vertex AI Function Declarations (tool definitions)
# ─────────────────────────────────────────────────────────────────────────────

ADD_MARKDOWN = FunctionDeclaration(
    name="add_markdown_section",
    description="Add a markdown cell — section heading, narrative, or insight bullets.",
    parameters={
        "type": "object",
        "properties": {
            "content": {
                "type": "string",
                "description": "Markdown text to insert into the notebook.",
            }
        },
        "required": ["content"],
    },
)

ADD_CODE = FunctionDeclaration(
    name="add_code_cell",
    description=(
        "Add a Python code cell to the notebook. "
        "Pre-available variables: df, target_col (may be None), "
        "PRIMARY_COLOR, SECONDARY_COLOR, ACCENT_COLOR, pd, np, plt, sns, stats. "
        "End every chart cell with plt.tight_layout() and plt.show()."
    ),
    parameters={
        "type": "object",
        "properties": {
            "code": {
                "type": "string",
                "description": "Runnable Python code to add.",
            },
            "purpose": {
                "type": "string",
                "description": "One-line description of what this cell does.",
            },
        },
        "required": ["code", "purpose"],
    },
)

FINISH = FunctionDeclaration(
    name="finish_notebook",
    description=(
        "Call this once all sections are written to signal the notebook is complete."
    ),
    parameters={
        "type": "object",
        "properties": {
            "summary": {
                "type": "string",
                "description": "2-3 sentence executive summary citing specific numbers.",
            }
        },
        "required": ["summary"],
    },
)

EDA_TOOLS = Tool(function_declarations=[ADD_MARKDOWN, ADD_CODE, FINISH])


# ─────────────────────────────────────────────────────────────────────────────
# Agent
# ─────────────────────────────────────────────────────────────────────────────

class EDAAgent:
    def __init__(
        self,
        project:    Optional[str] = None,
        location:   str = "us-central1",
        model_name: str = "gemini-2.5-flash",
    ):
        """
        Parameters
        ----------
        project    : GCP project ID (falls back to GOOGLE_CLOUD_PROJECT env var)
        location   : Vertex AI region
        model_name : Gemini model to use. Defaults to gemini-2.5-flash.
                     Other options: gemini-2.0-flash-001, gemini-1.5-pro-002
        """
        self.project    = project or os.environ.get("GOOGLE_CLOUD_PROJECT")
        self.location   = location
        self.model_name = model_name
        vertexai.init(project=self.project, location=self.location)

        self._gen_model = GenerativeModel(
            model_name=self.model_name,
            tools=[EDA_TOOLS],
            generation_config=GenerationConfig(temperature=0.2, max_output_tokens=8192),
        )

    def run(
        self,
        df:         pd.DataFrame,
        target_col: Optional[str] = None,
        goal:       Optional[str] = None,
        context:    Optional[str] = None,
        output:     str = "eda_report.ipynb",
        verbose:    bool = True,
    ) -> str:
        """
        Run the two-phase EDA agent and write a .ipynb notebook.

        Parameters
        ----------
        df         : Any tabular DataFrame
        target_col : Optional explicit target column name.
                     If omitted, Gemini infers the best one (or none).
        goal       : Optional plain-text analysis goal.
                     e.g. "analyse serve efficiency and win rates by surface"
        context    : Optional plain-text dataset description.
                     Explain what the dataset is, what the columns mean,
                     any domain-specific knowledge, coded values, etc.
                     e.g. "ATP tennis matches 2000-2023. The 'w_ace' column is
                     winner ace count. Surface codes: H=Hard, C=Clay, G=Grass."
        output     : Output path for the .ipynb file
        verbose    : Print progress

        Returns
        -------
        Absolute path to the saved notebook.
        """
        if verbose:
            print(f"▶ Dataset: {len(df):,} rows × {len(df.columns)} columns")
            print("▶ Computing statistics...")

        summary = _compute_summary(df, target_col)

        # ── Phase 1: planning ────────────────────────────────────────────────
        plan = _run_planning(
            model=self._gen_model,
            model_name=self.model_name,
            summary=summary,
            user_goal=goal,
            user_target=target_col,
            user_context=context,
            verbose=verbose,
        )

        # Resolve final target from plan if not explicitly provided
        resolved_target = target_col or plan.get("target_col")
        title           = plan.get("title", "EDA Report")

        nb = NotebookBuilder(title=title)

        # Data loading cell — self-contained CSV embed
        nb.add_code(f"""\
            import io
            _csv = {repr(df.to_csv(index=False)[:200_000])}
            df = pd.read_csv(io.StringIO(_csv))
            target_col = {repr(resolved_target)}
            print(f"Loaded {{len(df):,}} rows × {{len(df.columns)}} columns")
            if target_col and target_col in df.columns:
                print(f"Target: {{target_col}}")
                print(df[target_col].value_counts().to_string())
        """)

        # ── Phase 2: notebook generation ─────────────────────────────────────
        if verbose:
            print("  → Phase 2: generating notebook cells...")

        gen_prompt  = _build_generation_prompt(plan, summary)
        chat        = self._gen_model.start_chat(response_validation=False)
        pending_msg = gen_prompt   # first turn: plain string
        done        = False
        cell_count  = 0

        while not done:
            if verbose:
                print(f"  → Gemini writing (cells: {cell_count})...")

            response    = chat.send_message(pending_msg)
            fn_parts    = []   # collect Part objects for this turn

            # Check finish reason — 2 = MAX_TOKENS, handle gracefully
            candidate = response.candidates[0]
            finish_reason = getattr(candidate, "finish_reason", None)
            if finish_reason and str(finish_reason) in ("2", "FinishReason.MAX_TOKENS"):
                if verbose:
                    print("  ⚠ Response hit token limit — processing partial response and continuing...")

            for part in candidate.content.parts:
                # Gemini 2.5 may include thought/text parts — skip non-function parts
                fc = getattr(part, "function_call", None)
                if not fc or not getattr(fc, "name", None):
                    continue

                fn   = fc.name
                args = dict(fc.args)

                if fn == "add_markdown_section":
                    nb.add_markdown(args["content"])
                    cell_count += 1
                    if verbose:
                        preview = args["content"][:70].replace("\n", " ")
                        print(f"    + markdown : {preview}…")
                    fn_parts.append(self._fn_resp(fn, "added"))

                elif fn == "add_code_cell":
                    nb.add_code(args["code"])
                    cell_count += 1
                    if verbose:
                        print(f"    + code     : {args.get('purpose', '')}")
                    fn_parts.append(self._fn_resp(fn, "added"))

                elif fn == "finish_notebook":
                    nb.add_markdown(
                        f"---\n## Executive summary\n\n{args['summary']}\n\n"
                        f"*Domain: {plan.get('domain_label', plan.get('domain'))} · "
                        f"Generated by EDAAgent · Vertex AI / Gemini 2.0 Flash*"
                    )
                    done = True
                    if verbose:
                        print("  → finish_notebook called.")
                    fn_parts.append(self._fn_resp(fn, "complete"))

            if fn_parts:
                # Send all function responses as a single Content object
                pending_msg = Content(
                    role="user",
                    parts=fn_parts,
                )
            else:
                if verbose:
                    print("  → No more function calls — saving.")
                done = True

        nb.save(output)
        if verbose:
            print(f"\n✓ {cell_count} cells written  |  domain: {plan.get('domain_label')}")
            print(f"  Open: jupyter notebook {output}")
        return str(Path(output).resolve())

    @staticmethod
    def _fn_resp(name: str, result: str) -> "Part":
        """Return a Vertex AI Part containing a function response."""
        return Part.from_function_response(
            name=name,
            response={"result": result},
        )
